### PR TITLE
update gold data and score relatively high accuracy on all relations

### PR DESCRIPTION
**Pull request by lukehsiao**

### CODE REVIEW

**Comment by xiao-cheng** [comment]
what is the `input/abbyhtm` directory? Seems duplicate of `input/htm`

**Comment by lukehsiao** [comment]
Yeah I'm not sure. You added it in 541fe95. If we don't need it, I'll delete it in the next pull request.

**Comment by xiao-cheng** [comment]
Yeah let's get rid of it. Probably added for experimentation...

**Comment by lukehsiao** [comment]
Sounds good. I'll remove the directory.

**Pull request merged**
